### PR TITLE
Add a rightclick handler for map interaction

### PR DESCRIPTION
**Pull request by pludov**
This PR adds a callback to get notified for right click in the map. The callback will receive an event object including the location of the click (RA, DEC) and the id of the closest marker if present.

This partially resolves issue #25 since it provides RA and DEC in the callback.

### CODE REVIEW

**Comment by slowe** [comment]
Good work pludov. I'd almost be tempted to do some of this through a plugin to keep the main file size down for those who don't need a context menu.

**Comment by slowe** [comment]
Having said that... I've just seen your comment on https://github.com/slowe/VirtualSky/issues/25#issuecomment-517988969 and you are right that it solves that.

**Comment by slowe** [comment]
@pludov Would you object to me renaming the `rightclick` event as `contextmenu` just to keep it matching with https://developer.mozilla.org/en-US/docs/Web/API/Element/contextmenu_event ? That also avoids it containing "click" which is very mouse-centric.

**Comment by pludov** [comment]
No objection on my side !

Le 6 août 2019 14:54:19 GMT+02:00, Stuart Lowe <notifications@github.com> a écrit :
>@pludov Would you object to me renaming the `rightclick` event as
>`contextmenu` just to keep it matching with
>https://developer.mozilla.org/en-US/docs/Web/API/Element/contextmenu_event
>?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/slowe/VirtualSky/pull/58#issuecomment-518656525

-- 
Envoyé de mon téléphone Android avec K-9 Mail. Excusez la brièveté.

**Comment by slowe** [comment]
OK. I've made some changes and cleaned up the code a bit using jshint.com. Thanks for all your contributions @pludov! Make sure to update before making more changes. :)

**Pull request merged**
